apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: migrator-netpolicy
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app: migrator
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: database
    ports:
      - port: 5432
        protocol: TCP