apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secrets.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.database.secrets.name }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.database.secrets.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.secrets.password | quote }}
  POSTGRES_DB: {{ .Values.database.secrets.db | quote }}