apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.database.name }}
    release: {{ .Release.Name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.database.name }}
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.database.service.ports.port }}
      protocol: {{ .Values.database.service.ports.protocol }}
      targetPort: {{ .Values.database.statefulset.containerPort }}