apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  maxReplicas: {{ .Values.restapi.podAutoscaler.maxReplicas }}
  metrics:
    - resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # Autoscaler will adjust the number of pods so they each utilize 50% of requested CPU.
      type: Resource
  minReplicas: {{ .Values.restapi.podAutoscaler.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}

