{{/*apiVersion: v1*/}}
{{/*kind: LimitRange*/}}
{{/*metadata:*/}}
{{/*  name: {{ .Chart.Name }}*/}}
{{/*  namespace: {{ .Release.Namespace }}*/}}
{{/*  labels:*/}}
{{/*    app: {{ .Chart.Name }}*/}}
{{/*    release: {{ .Release.Name }}*/}}
{{/*spec:*/}}
{{/*  limits:*/}}
{{/*    - type: Pod*/}}
{{/*      min:*/}}
{{/*        cpu: {{ .Values.limitRange.pod.min.cpu }}*/}}
{{/*        memory: {{ .Values.limitRange.pod.min.memory }}*/}}
{{/*      max:*/}}
{{/*        cpu: {{ .Values.limitRange.pod.max.cpu }}*/}}
{{/*        memory: {{ .Values.limitRange.pod.max.memory }}*/}}
{{/*    - type: Container*/}}
{{/*      defaultRequest:*/}}
{{/*        cpu: {{ .Values.limitRange.container.defaultRequest.cpu }}*/}}
{{/*        memory: {{ .Values.limitRange.container.defaultRequest.memory }}*/}}
{{/*      default:*/}}
{{/*        cpu: {{ .Values.limitRange.container.default.cpu }}*/}}
{{/*        memory: {{ .Values.limitRange.container.default.memory }}*/}}
{{/*      min:*/}}
{{/*        cpu: {{ .Values.limitRange.container.min.cpu }}*/}}
{{/*        memory: {{ .Values.limitRange.container.min.memory }}*/}}
{{/*      max:*/}}
{{/*        cpu: {{ .Values.limitRange.container.max.cpu }}*/}}
{{/*        memory: {{ .Values.limitRange.container.max.memory }}*/}}