apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.migrator.secrets.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.migrator.secrets.name }}
    release: {{ .Release.Name }}
stringData:
  migrator.conf: |
    {{ .Values.migrator.secrets.dbUser }}
    {{ .Values.migrator.secrets.dbHost }}
    {{ .Values.migrator.secrets.dbName }}
    {{ .Values.migrator.secrets.dbPort }}
    {{ .Values.migrator.secrets.dbPassword }}
    {{ .Values.migrator.secrets.dbSSL }}
    {{ .Values.migrator.secrets.dbDirection }}