name: Golang CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  Clone-down:
    name: Clone down repo
    runs-on: ubuntu-latest
    container: golang:1.21.1-alpine3.18
    steps:
    - uses: actions/checkout@v4
    - name: Upload Repo
      uses: actions/upload-artifact@v3
      with:
        name: code
        path: .
  Build:
      runs-on: ubuntu-latest
      needs: Clone-down
      container: golang:1.21.1-alpine3.18
      steps:
      - name: Download code
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .
      - name: Build
        run: |
          cd app/restapi
          go build -gcflags="-N -l" ./cmd/server/server.go
          echo "Server was build successfully."
          go build -gcflags="-N -l" ./cmd/client/client.go
          echo "Client was build successfully."
          go build -gcflags="-N -l" ./cmd/healthchecker/healthchecker.go
          echo "Health checker was build successfully."
      - name: Unit Test
        run: |
          cd app/restapi
          go test ./...
      - name: Upload Repo
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: .
  Docker-image:
      runs-on: ubuntu-latest
      needs: [Build]
      permissions:
        packages: write
      steps:
      - name: Download code
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build Docker
        run: |
          [[ -z "${GIT_COMMIT}" ]] && Tag='local' || Tag="${GIT_COMMIT::8}"
          [[ -z "${{ secrets.DOCKER_HUB_USERNAME }}" ]] && DockerRepo='' || DockerRepo="ghcr.io/${{ secrets.DOCKER_HUB_USERNAME }}/"
          docker build -t "${DockerRepo}migrator:latest" -t "${DockerRepo}migrator:1.0-$Tag" app/migrator/
          docker build -t "${DockerRepo}restapi:latest" -t "${DockerRepo}restapi:1.0-$Tag" app/restapi/
      - name: Push Docker
        run: | 
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/restapi:1.0-${GIT_COMMIT::8}"
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/restapi:latest"
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/migrator:1.0-${GIT_COMMIT::8}"
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/migrator:latest" &
          wait
